name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Download Dependencies
        run: ./gradlew build --no-daemon

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Start Android Emulator
        run: |
          sudo apt-get update
          sudo apt-get install -y android-tools-adb
          ./emulator-headless -avd test -no-window -no-audio -no-boot-anim &
          adb wait-for-device
          adb shell input keyevent 82 &
        env:
          API_LEVEL: 30
          TARGET: default
          ABI: x86_64
          PROFILE: test

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-daemon

      - name: Run Instrumented Tests
        run: ./gradlew connectedAndroidTest --no-daemon

      - name: Stop Android Emulator
        if: always()
        run: adb emu kill

      - name: Clear Emulator AVD files
        if: always()
        run: rm -rf ${{ github.workspace }}/.android/avdmon