name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3
          target: android-30
          ndk: 21.4.7075529

      - name: Install Emulator and System Image
        run: |
          sdkmanager "system-images;android-30;google_apis;x86_64"
          sdkmanager "platform-tools"
          sdkmanager "emulator"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Download Dependencies
        run: ./gradlew build --no-daemon

#      - name: Create Android Emulator AVD
#        run: |
#          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" -c 100M

#      - name: Start Android Emulator
#        run: |
#          emulator -avd test -no-window -no-audio -no-boot-anim &
#          adb wait-for-device
#          adb shell input keyevent 82 &
#        env:
#          API_LEVEL: 30
#          TARGET: default
#          ABI: x86_64
#          PROFILE: test

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-daemon

#      - name: Run Instrumented Tests
#        run: ./gradlew connectedAndroidTest --no-daemon

#      - name: Stop Android Emulator
#        if: always()
#        run: adb emu kill

      - name: Clear Emulator AVD files
        if: always()
        run: rm -rf ${{ github.workspace }}/.android/avdmon
